import type { AdminProfile, SectionConfig } from "./types";

export const sections: SectionConfig[] = [
  {
    id: "dashboard",
    href: "/",
    icon: "LayoutDashboard",
    mode: "dashboard",
    title: { ar: "��������", en: "Dashboard" },
    description: {
      ar: "����� ������� ������� ���������� ������.",
      en: "Daily operating numbers and alerts.",
    },
    allowedRoles: ["admin", "support_agent"],
  },
  {
    id: "merchant-approvals",
    href: "/admin/merchant-approvals",
    icon: "Store",
    mode: "table",
    source: "admin_merchants_readable",
    sourceKind: "view",
    editableTable: "merchants",
    orderBy: "created_at",
    title: { ar: "������� �������", en: "Merchant approvals" },
    description: {
      ar: "������ ������ ������ ���� ��������� ����� �� ��� �����.",
      en: "Review merchant data and approve or reject.",
    },
    searchKeys: [
      "store_name",
      "owner_name",
      "owner_mobile",
      "account_email",
      "category_name_ar",
    ],
    actions: ["review_details", "approve_merchant", "reject_merchant"],
    allowedRoles: ["admin"],
    columns: [
      { key: "store_name", label: { ar: "������", en: "Store" } },
      { key: "owner_name", label: { ar: "������", en: "Owner" } },
      {
        key: "owner_mobile",
        label: { ar: "������ ������", en: "Owner mobile" },
      },
      { key: "category_name_ar", label: { ar: "�����", en: "Category" } },
      {
        key: "approval_status_ar",
        label: { ar: "������", en: "Status" },
        tone: "status",
      },
      {
        key: "rejection_reason",
        label: { ar: "��� �����", en: "Rejection reason" },
        tone: "long",
      },
      {
        key: "created_at",
        label: { ar: "����� �������", en: "Created" },
        tone: "date",
      },
    ],
  },
  {
    id: "branch-approvals",
    href: "/admin/branch-approvals",
    icon: "MapPin",
    mode: "table",
    source: "admin_branches_readable",
    sourceKind: "view",
    editableTable: "branches",
    orderBy: "created_at",
    title: { ar: "������� ������", en: "Branch approvals" },
    description: {
      ar: "������ ������ ������� ��� ������ �� ����� �����.",
      en: "Review new branches before search visibility.",
    },
    searchKeys: [
      "branch_name",
      "store_name",
      "city_name",
      "governorate_name",
      "manager_mobile",
    ],
    actions: ["review_details", "approve_branch", "reject_branch"],
    allowedRoles: ["admin"],
    columns: [
      { key: "branch_name", label: { ar: "�����", en: "Branch" } },
      { key: "store_name", label: { ar: "������", en: "Store" } },
      { key: "city_name", label: { ar: "�������", en: "City" } },
      { key: "governorate_name", label: { ar: "��������", en: "Governorate" } },
      {
        key: "manager_mobile",
        label: { ar: "����� �����", en: "Branch contact" },
      },
      {
        key: "approval_status_ar",
        label: { ar: "������", en: "Status" },
        tone: "status",
      },
      {
        key: "created_at",
        label: { ar: "����� �������", en: "Created" },
        tone: "date",
      },
    ],
  },
  {
    id: "shipping-companies",
    href: "/admin/shipping-companies",
    icon: "Truck",
    mode: "table",
    source: "admin_merchant_shipping_companies_readable",
    sourceKind: "view",
    editableTable: "merchant_shipping_companies",
    orderBy: "created_at",
    title: { ar: "����� �����", en: "Shipping Companies" },
    description: {
      ar: "������ ����� ����� ���� ������� �������.",
      en: "Monitor shipping companies added by merchants.",
    },
    searchKeys: ["store_name", "company_name"],
    actions: [], // Read-only for admins for now
    allowedRoles: ["admin", "support_agent"],
    supportPermission: "shipping_companies",
    columns: [
      { key: "store_name", label: { ar: "������", en: "Store" } },
      { key: "company_name", label: { ar: "���� �����", en: "Company" } },
      { key: "batches_count", label: { ar: "��� ��������", en: "Batches count" } },
      { key: "status_ar", label: { ar: "������", en: "Status" }, tone: "status" },
      { key: "created_at", label: { ar: "����� �������", en: "Created" }, tone: "date" },
    ],
  },
  {
    id: "users",
    href: "/admin/users",
    icon: "Users",
    mode: "table",
    source: "admin_users_readable",
    sourceKind: "view",
    editableTable: "users",
    orderBy: "created_at",
    title: { ar: "����������", en: "Users" },
    description: {
      ar: "��ˡ ������ ����� �������ʡ ���� �� ����� ����������.",
      en: "Search accounts, roles, and block status.",
    },
    searchKeys: ["full_name", "mobile", "primary_email", "role_ar"],
    actions: [
      "block_user",
      "unblock_user",
      "set_user_password",
      "delete_user_account",
    ],
    allowedRoles: ["admin"],
    columns: [
      { key: "full_name", label: { ar: "�����", en: "Name" } },
      { key: "mobile", label: { ar: "��������", en: "Mobile" } },
      { key: "primary_email", label: { ar: "�������", en: "Email" } },
      { key: "role_ar", label: { ar: "�����", en: "Role" }, tone: "status" },
      {
        key: "account_status_ar",
        label: { ar: "������", en: "Account" },
        tone: "status",
      },
      { key: "created_at", label: { ar: "���", en: "Created" }, tone: "date" },
    ],
  },
  {
    id: "staff",
    href: "/admin/staff",
    icon: "Users",
    mode: "staff",
    title: {
      ar: "\u0627\u0644\u0641\u0631\u064a\u0642 \u0648\u0627\u0644\u0635\u0644\u0627\u062d\u064a\u0627\u062a",
      en: "Team and permissions",
    },
    description: {
      ar: "\u0625\u0636\u0627\u0641\u0629 \u0645\u062f\u064a\u0631 \u0623\u0648 \u0645\u0648\u0638\u0641 \u062f\u0639\u0645\u060c \u0648\u0643\u062a\u0627\u0628\u0629 \u0627\u0633\u0645 \u0627\u0644\u0631\u062a\u0628\u0629 \u0648\u062a\u062d\u062f\u064a\u062f \u0627\u0644\u0635\u0644\u0627\u062d\u064a\u0627\u062a.",
      en: "Add admins or support staff, set rank labels, and choose permissions.",
    },
    allowedRoles: ["admin"],
  },
  {
    id: "categories",
    href: "/admin/categories",
    icon: "Tags",
    mode: "table",
    source: "categories",
    sourceKind: "table",
    editableTable: "categories",
    editableFields: [
      "name_ar",
      "name_en",
      "parent_id",
      "display_order",
      "is_active",
    ],
    orderBy: "display_order",
    title: { ar: "���������", en: "Categories" },
    description: {
      ar: "����� ������ �������� �������� ��� ��� �������.",
      en: "Manage the full category tree.",
    },
    searchKeys: ["name_ar", "name_en"],
    actions: ["edit_row", "toggle_active", "delete_row"],
    allowedRoles: ["admin"],
    columns: [
      { key: "name_ar", label: { ar: "����� ������", en: "Arabic name" } },
      { key: "name_en", label: { ar: "����� ���������", en: "English name" } },
      { key: "parent_id", label: { ar: "����", en: "Parent" }, tone: "long" },
      { key: "display_order", label: { ar: "�������", en: "Order" } },
      { key: "is_active", label: { ar: "����", en: "Active" }, tone: "status" },
    ],
  },
  {
    id: "cities",
    href: "/admin/cities",
    icon: "Map",
    mode: "table",
    source: "cities",
    sourceKind: "table",
    editableTable: "cities",
    editableFields: [
      "country_ar",
      "country_en",
      "name_ar",
      "name_en",
      "governorate_ar",
      "governorate_en",
      "currency_code",
      "currency_name_ar",
      "currency_name_en",
      "display_order",
      "is_active",
    ],
    orderBy: "country_ar",
    title: { ar: "����� ��������", en: "Cities and areas" },
    description: {
      ar: "����� ������ ������� �������.",
      en: "Manage operating areas and expansion.",
    },
    searchKeys: [
      "country_ar",
      "country_en",
      "name_ar",
      "name_en",
      "governorate_ar",
      "governorate_en",
      "currency_code",
      "currency_name_ar",
      "currency_name_en",
    ],
    actions: ["edit_row", "toggle_active", "delete_row"],
    allowedRoles: ["admin"],
    columns: [
      { key: "country_ar", label: { ar: "�����", en: "Country" } },
      { key: "currency_name_ar", label: { ar: "������", en: "Currency" } },
      { key: "currency_code", label: { ar: "��� ������", en: "Currency code" } },
      { key: "governorate_ar", label: { ar: "��������", en: "Governorate" } },
      { key: "name_ar", label: { ar: "�������", en: "City" } },
      { key: "display_order", label: { ar: "�������", en: "Order" } },
      { key: "name_en", label: { ar: "City EN", en: "City EN" } },
      {
        key: "is_active",
        label: { ar: "�����", en: "Active" },
        tone: "status",
      },
    ],
  },
  {
    id: "stores",
    href: "/admin/stores",
    icon: "Building2",
    mode: "table",
    source: "admin_merchants_readable",
    sourceKind: "view",
    orderBy: "updated_at",
    title: { ar: "����� �������", en: "Stores" },
    description: {
      ar: "������ ������ѡ �����ڡ �������ʡ ������ ��������.",
      en: "Store data, branches, products, and billing.",
    },
    searchKeys: [
      "store_name",
      "owner_name",
      "contact_mobile",
      "billing_preference_ar",
    ],
    allowedRoles: ["admin"],
    columns: [
      { key: "store_name", label: { ar: "������", en: "Store" } },
      { key: "contact_mobile", label: { ar: "�������", en: "Contact" } },
      {
        key: "approval_status_ar",
        label: { ar: "��������", en: "Approval" },
        tone: "status",
      },
      {
        key: "billing_preference_ar",
        label: { ar: "��������", en: "Billing" },
        tone: "status",
      },
      {
        key: "updated_at",
        label: { ar: "��� �����", en: "Updated" },
        tone: "date",
      },
    ],
  },
  {
    id: "store-catalog",
    href: "/admin/store-catalog",
    icon: "Images",
    mode: "catalog",
    title: {
      ar: "����� ������� ���������",
      en: "Store and product moderation",
    },
    description: {
      ar: "���� ������� ������ ����� �� ���� ������� �������� ������ ���� �������.",
      en: "Browse stores visually, review product images, and remove violations.",
    },
    allowedRoles: ["admin"],
  },
  {
    id: "orders",
    href: "/admin/orders",
    icon: "ClipboardList",
    mode: "table",
    source: "admin_orders_readable",
    sourceKind: "view",
    orderBy: "created_at",
    title: { ar: "�������", en: "Orders" },
    description: {
      ar: "�� ������� ������� ����� ������� ����� ������� ������.",
      en: "All orders, accepted offer, confirmation, and payment.",
    },
    searchKeys: ["buyer_name", "buyer_mobile", "store_name", "status_ar"],
    allowedRoles: ["admin", "support_agent"],
    supportPermission: "orders",
    columns: [
      { key: "buyer_name", label: { ar: "������", en: "Buyer" } },
      { key: "store_name", label: { ar: "������", en: "Store" } },
      {
        key: "status_ar",
        label: { ar: "���� �����", en: "Status" },
        tone: "status",
      },
      {
        key: "payment_status",
        label: { ar: "�����", en: "Payment" },
        tone: "status",
      },
      {
        key: "selected_subtotal_snapshot",
        label: { ar: "��������", en: "Subtotal" },
        tone: "money",
      },
      { key: "created_at", label: { ar: "�������", en: "Date" }, tone: "date" },
    ],
  },
  {
    id: "suspicious-matches",
    hidden: true,
    href: "/admin/suspicious-matches",
    icon: "SearchCheck",
    mode: "table",
    source: "admin_offer_items_readable",
    sourceKind: "view",
    orderBy: "created_at",
    title: { ar: "������� ����� ����", en: "Low confidence matches" },
    description: {
      ar: "������ ������ ��� ��� ������ ��� ����� ��������.",
      en: "Review low-confidence offer items.",
    },
    searchKeys: [
      "store_name",
      "product_name",
      "requested_name",
      "matched_name_snapshot",
    ],
    allowedRoles: ["admin"],
    columns: [
      { key: "store_name", label: { ar: "������", en: "Store" } },
      { key: "requested_name", label: { ar: "�������", en: "Requested" } },
      { key: "matched_name_snapshot", label: { ar: "�������", en: "Matched" } },
      {
        key: "line_total_snapshot",
        label: { ar: "��������", en: "Total" },
        tone: "money",
      },
      {
        key: "match_confidence",
        label: { ar: "�����", en: "Confidence" },
        tone: "status",
      },
    ],
  },
  {
    id: "ai-reads",
    href: "/admin/ai-reads",
    icon: "FileScan",
    mode: "table",
    source: "admin_ai_reading_log",
    sourceKind: "view",
    orderBy: "created_at",
    title: { ar: "������ ������ ���������", en: "AI reads" },
    description: {
      ar: "������ ������� �������� ������� ����� ��������.",
      en: "Real request and file analysis readings.",
    },
    searchKeys: [
      "owner_name",
      "owner_mobile",
      "reading_type_ar",
      "source_ar",
      "status_ar",
      "error_code",
    ],
    allowedRoles: ["admin"],
    columns: [
      { key: "owner_name", label: { ar: "��������", en: "User" } },
      {
        key: "reading_type_ar",
        label: { ar: "��� �������", en: "Reading type" },
        tone: "status",
      },
      {
        key: "source_ar",
        label: { ar: "������", en: "Source" },
        tone: "status",
      },
      {
        key: "status_ar",
        label: { ar: "������", en: "Status" },
        tone: "status",
      },
      { key: "confidence", label: { ar: "�����", en: "Confidence" } },
      { key: "error_code", label: { ar: "��� �����", en: "Error code" } },
      { key: "created_at", label: { ar: "�������", en: "Date" }, tone: "date" },
    ],
  },
  {
    id: "support",
    href: "/admin/support",
    icon: "Headphones",
    mode: "support",
    title: { ar: "���� �������", en: "Support" },
    description: {
      ar: "����� ��������� ������� �� ����� ����� ������.",
      en: "Transferred bot conversations and live replies.",
    },
    allowedRoles: ["admin", "support_agent"],
    supportPermission: "support_chats",
  },
  {
    id: "broadcast",
    href: "/admin/broadcast",
    icon: "BellRing",
    mode: "broadcast",
    title: { ar: "����� �����", en: "Send notification" },
    description: {
      ar: "����� ����� ���� ���� �� ��� ������� ����� Firebase Push ���������� ���������.",
      en: "Send a manual notification to the in-app bell and Firebase Push.",
    },
    allowedRoles: ["admin"],
  },
  {
    id: "ads",
    href: "/admin/ads",
    icon: "Images",
    mode: "table",
    source: "ads_banners",
    sourceKind: "table",
    editableTable: "ads_banners",
    editableFields: [
      "image_url",
      "target_url",
      "placement",
      "target_country_ar",
      "target_governorate_ar",
      "target_city_ar",
      "sort_order",
      "starts_at",
      "ends_at",
      "is_active",
    ],
    orderBy: "created_at",
    title: {
      ar: "\u0627\u0644\u0625\u0639\u0644\u0627\u0646\u0627\u062a",
      en: "Ads",
    },
    description: {
      ar: "\u0625\u062f\u0627\u0631\u0629 \u0625\u0639\u0644\u0627\u0646\u0627\u062a \u0627\u0644\u062a\u0637\u0628\u064a\u0642: \u0635\u0648\u0631\u0629 \u0627\u0644\u0625\u0639\u0644\u0627\u0646\u060c \u0644\u064a\u0646\u0643 \u0627\u0644\u0645\u0639\u0644\u0646\u060c \u0648\u0645\u064a\u0639\u0627\u062f \u0627\u0644\u0638\u0647\u0648\u0631.",
      en: "Manage in-app ad images, advertiser links, and schedules.",
    },
    searchKeys: [
      "image_url",
      "target_url",
      "placement",
      "target_country_ar",
      "target_governorate_ar",
      "target_city_ar",
    ],
    actions: ["edit_row", "toggle_active", "delete_row"],
    allowedRoles: ["admin"],
    columns: [
      {
        key: "image_url",
        label: {
          ar: "\u0635\u0648\u0631\u0629 \u0627\u0644\u0625\u0639\u0644\u0627\u0646",
          en: "Image",
        },
        tone: "long",
      },
      {
        key: "target_url",
        label: {
          ar: "\u0644\u064a\u0646\u0643 \u0627\u0644\u0645\u0639\u0644\u0646",
          en: "Advertiser link",
        },
        tone: "long",
      },
      {
        key: "placement",
        label: {
          ar: "\u0645\u0643\u0627\u0646 \u0627\u0644\u0638\u0647\u0648\u0631",
          en: "Placement",
        },
        tone: "status",
      },
      { key: "target_country_ar", label: { ar: "�����", en: "Country" } },
      {
        key: "target_governorate_ar",
        label: { ar: "��������", en: "Governorate" },
      },
      { key: "target_city_ar", label: { ar: "�������", en: "City" } },
      {
        key: "sort_order",
        label: {
          ar: "\u0627\u0644\u062a\u0631\u062a\u064a\u0628",
          en: "Order",
        },
      },
      {
        key: "is_active",
        label: { ar: "\u0645\u0641\u0639\u0644", en: "Active" },
        tone: "status",
      },
    ],
  },
  {
    id: "complaints",
    href: "/admin/complaints",
    icon: "MessagesSquare",
    mode: "table",
    source: "admin_support_complaints_readable",
    sourceKind: "view",
    orderBy: "created_at",
    title: { ar: "������� ���������", en: "Complaints" },
    description: {
      ar: "������� �������� �������� ����� ����.",
      en: "Open and escalated complaints.",
    },
    searchKeys: [
      "reporter_name",
      "reporter_mobile",
      "store_name",
      "title",
      "body",
      "status",
      "priority",
      "target_type",
    ],
    allowedRoles: ["admin", "support_agent"],
    supportPermission: "complaints",
    columns: [
      { key: "reporter_name", label: { ar: "������", en: "Reporter" } },
      { key: "store_name", label: { ar: "������", en: "Store" } },
      { key: "title", label: { ar: "�������", en: "Title" } },
      {
        key: "target_type",
        label: { ar: "�����", en: "Type" },
        tone: "status",
      },
      { key: "status", label: { ar: "������", en: "Status" }, tone: "status" },
      {
        key: "priority",
        label: { ar: "��������", en: "Priority" },
        tone: "status",
      },
      { key: "created_at", label: { ar: "�������", en: "Date" }, tone: "date" },
    ],
  },
  {
    id: "knowledge",
    href: "/admin/knowledge",
    icon: "BookOpen",
    mode: "table",
    source: "knowledge_base",
    sourceKind: "table",
    editableTable: "knowledge_base",
    editableFields: [
      "title_ar",
      "title_en",
      "content_ar",
      "content_en",
      "category",
      "is_active",
    ],
    orderBy: "updated_at",
    title: { ar: "����� ����� �����", en: "Bot knowledge base" },
    description: {
      ar: "����� ����� ����� ������ ����� ��� embeddings ��� �������.",
      en: "Bot training content and embedding refresh flags.",
    },
    searchKeys: ["title_ar", "title_en", "content_ar", "category"],
    actions: ["edit_row", "toggle_active"],
    allowedRoles: ["admin", "support_agent"],
    supportPermission: "knowledge_base",
    columns: [
      { key: "title_ar", label: { ar: "�������", en: "Title" } },
      {
        key: "category",
        label: { ar: "�������", en: "Category" },
        tone: "status",
      },
      { key: "is_active", label: { ar: "����", en: "Active" }, tone: "status" },
      {
        key: "needs_embedding",
        label: { ar: "����� �����", en: "Needs embedding" },
        tone: "status",
      },
      {
        key: "updated_at",
        label: { ar: "��� �����", en: "Updated" },
        tone: "date",
      },
    ],
  },
  {
    id: "reports",
    href: "/admin/reports",
    icon: "ChartNoAxesCombined",
    mode: "reports",
    title: { ar: "��������", en: "Reports" },
    description: {
      ar: "����ʡ ����� ���ɡ ������ҡ RFQ� �������.",
      en: "Orders, active stores, categories, RFQ, and commissions.",
    },
    allowedRoles: ["admin"],
  },
  {
    id: "content-moderation",
    href: "/admin/content-moderation",
    icon: "ShieldCheck",
    mode: "table",
    source: "content_moderation_terms",
    sourceKind: "table",
    editableTable: "content_moderation_terms",
    editableFields: [
      "term",
      "language",
      "match_type",
      "category",
      "severity",
      "notes",
      "is_active",
    ],
    orderBy: "updated_at",
    title: { ar: "����� �������", en: "Content moderation" },
    description: {
      ar: "����� ������� ��������� ���� ���� ������� �� �������� ��� ��������.",
      en: "Manage blocked words and phrases used for messages and product content.",
    },
    searchKeys: [
      "term",
      "language",
      "match_type",
      "category",
      "severity",
      "notes",
    ],
    actions: ["edit_row", "toggle_active", "delete_row"],
    allowedRoles: ["admin"],
    columns: [
      { key: "term", label: { ar: "������ �� �������", en: "Term" } },
      {
        key: "language",
        label: { ar: "�����", en: "Language" },
        tone: "status",
      },
      {
        key: "match_type",
        label: { ar: "����� �����", en: "Match type" },
        tone: "status",
      },
      {
        key: "category",
        label: { ar: "�������", en: "Category" },
        tone: "status",
      },
      {
        key: "severity",
        label: { ar: "�������", en: "Action" },
        tone: "status",
      },
      { key: "is_active", label: { ar: "����", en: "Active" }, tone: "status" },
      {
        key: "updated_at",
        label: { ar: "��� �����", en: "Updated" },
        tone: "date",
      },
    ],
  },
  {
    id: "monetization",
    href: "/admin/monetization",
    icon: "BadgeDollarSign",
    mode: "settings",
    source: "feature_flags",
    sourceKind: "table",
    editableTable: "feature_flags",
    editableFields: [
      "description_ar",
      "description_en",
      "is_enabled",
      "configuration",
    ],
    orderBy: "key",
    title: { ar: "���������� ����������", en: "Monetization" },
    description: {
      ar: "Feature flags ���� �������� ������ �����.",
      en: "Feature flags, plans, and payment providers.",
    },
    searchKeys: ["key", "description_ar", "description_en"],
    actions: ["edit_row", "toggle_active"],
    allowedRoles: ["admin"],
  },
  {
    id: "payments",
    href: "/admin/payments",
    icon: "CreditCard",
    mode: "table",
    source: "admin_payment_transactions_readable",
    sourceKind: "view",
    orderBy: "created_at",
    title: { ar: "������� �����", en: "Payments" },
    description: {
      ar: "����� ����� ��������� ������ ��� ����� �����.",
      en: "Payment statuses across providers.",
    },
    searchKeys: [
      "user_name",
      "store_name",
      "provider",
      "status",
      "external_reference",
    ],
    allowedRoles: ["admin"],
    columns: [
      { key: "user_name", label: { ar: "��������", en: "User" } },
      { key: "store_name", label: { ar: "������", en: "Store" } },
      {
        key: "provider",
        label: { ar: "����� �����", en: "Provider" },
        tone: "status",
      },
      { key: "amount", label: { ar: "������", en: "Amount" }, tone: "money" },
      { key: "status", label: { ar: "������", en: "Status" }, tone: "status" },
      { key: "created_at", label: { ar: "�������", en: "Date" }, tone: "date" },
    ],
  },
  {
    id: "referrals",
    href: "/admin/referrals",
    icon: "Gift",
    mode: "table",
    source: "admin_referral_rewards_readable",
    sourceKind: "view",
    orderBy: "created_at",
    title: { ar: "�������� ���������", en: "Referrals and rewards" },
    description: {
      ar: "������ ������ϡ ��������� ������ɡ ������ ��������.",
      en: "Track codes, confirmed registrations, and rewards.",
    },
    searchKeys: [
      "referrer_name",
      "rewarded_user_name",
      "referral_code",
      "delivery_status",
    ],
    allowedRoles: ["admin"],
    columns: [
      { key: "referrer_name", label: { ar: "���� ������", en: "Referrer" } },
      {
        key: "rewarded_user_name",
        label: { ar: "�������", en: "Rewarded user" },
      },
      {
        key: "referral_code",
        label: { ar: "�����", en: "Code" },
        tone: "status",
      },
      {
        key: "reward_type",
        label: { ar: "��������", en: "Reward" },
        tone: "status",
      },
      {
        key: "delivery_status",
        label: { ar: "�������", en: "Delivery" },
        tone: "status",
      },
      { key: "created_at", label: { ar: "�������", en: "Date" }, tone: "date" },
    ],
  },
  {
    id: "audit",
    href: "/admin/audit",
    icon: "ShieldCheck",
    mode: "table",
    source: "admin_audit_logs_readable",
    sourceKind: "view",
    orderBy: "created_at",
    title: { ar: "��� ��������", en: "Audit logs" },
    description: {
      ar: "�� ����� ���� ���� ��� ��������.",
      en: "Sensitive actions appear here for review.",
    },
    searchKeys: [
      "actor_name",
      "actor_email",
      "action",
      "target_table",
      "target_id",
    ],
    allowedRoles: ["admin"],
    columns: [
      { key: "actor_name", label: { ar: "�������", en: "Actor" } },
      { key: "action", label: { ar: "�������", en: "Action" }, tone: "status" },
      {
        key: "target_table",
        label: { ar: "������", en: "Table" },
        tone: "status",
      },
      { key: "target_id", label: { ar: "�����", en: "Target" }, tone: "long" },
      { key: "created_at", label: { ar: "�������", en: "Date" }, tone: "date" },
    ],
  },
];

export function findSection(id?: string) {
  return sections.find((section) => section.id === id) ?? sections[0];
}

export function sectionIsAllowed(
  section: SectionConfig,
  profile: AdminProfile | null,
) {
  if (section.hidden) {
    return false;
  }
  if (!profile) {
    return false;
  }

  if (profile.role === "admin" && profile.permissions.__limit_admin !== true) {
    return true;
  }

  const permissionKey = permissionKeyForSection(section);
  if (profile.permissions[permissionKey] === true) {
    return true;
  }

  if (section.allowedRoles && !section.allowedRoles.includes(profile.role)) {
    return false;
  }

  return profile.role === "admin" && profile.permissions.__limit_admin !== true;
}

export function visibleSections(profile: AdminProfile | null) {
  return sections.filter((section) => sectionIsAllowed(section, profile));
}

function permissionKeyForSection(section: SectionConfig) {
  return section.supportPermission ?? section.id.replace(/-/g, "_");
}
