import type { AdminProfile, SectionConfig } from "./types";

export const sections: SectionConfig[] = [
  {
    id: "dashboard",
    href: "/",
    icon: "LayoutDashboard",
    mode: "dashboard",
    title: { ar: "لوحة التحكم", en: "Dashboard" },
    description: {
      ar: "ملخص أرقام التشغيل اليومية والتنبيهات والمهام التي تحتاج متابعة.",
      en: "Daily operating numbers, alerts, and items that need attention.",
    },
    allowedRoles: ["admin", "support_agent"],
  },
  {
    id: "merchant-approvals",
    href: "/admin/merchant-approvals",
    icon: "Store",
    mode: "table",
    source: "admin_active_merchants_readable",
    sourceKind: "view",
    editableTable: "merchants",
    orderBy: "created_at",
    title: { ar: "موافقات المتاجر", en: "Merchant approvals" },
    description: {
      ar: "مراجعة بيانات المتجر وهوية المالك وواجهة المتجر واتخاذ قرار القبول أو الرفض.",
      en: "Review store details, owner identity, and storefront before approving or rejecting.",
    },
    searchKeys: [
      "store_name",
      "owner_name",
      "owner_mobile",
      "account_email",
      "category_name_ar",
    ],
    actions: ["review_details", "approve_merchant", "reject_merchant"],
    allowedRoles: ["admin"],
    columns: [
      { key: "store_name", label: { ar: "المتجر", en: "Store" } },
      { key: "owner_name", label: { ar: "المالك", en: "Owner" } },
      {
        key: "owner_mobile",
        label: { ar: "جوال المالك", en: "Owner mobile" },
      },
      { key: "category_name_ar", label: { ar: "القسم", en: "Category" } },
      {
        key: "approval_status_ar",
        label: { ar: "الحالة", en: "Status" },
        tone: "status",
      },
      {
        key: "rejection_reason",
        label: { ar: "سبب الرفض", en: "Rejection reason" },
        tone: "long",
      },
      {
        key: "created_at",
        label: { ar: "تاريخ الإنشاء", en: "Created" },
        tone: "date",
      },
    ],
  },
  {
    id: "branch-approvals",
    href: "/admin/branch-approvals",
    icon: "MapPin",
    mode: "table",
    source: "admin_branches_readable",
    sourceKind: "view",
    editableTable: "branches",
    orderBy: "created_at",
    title: { ar: "موافقات الفروع", en: "Branch approvals" },
    description: {
      ar: "مراجعة بيانات الفروع وهوية مدير الفرع وواجهة الفرع قبل ظهورها للمستخدمين.",
      en: "Review branch details, manager identity, and storefront before making them visible to users.",
    },
    searchKeys: [
      "branch_name",
      "store_name",
      "city_name",
      "governorate_name",
      "manager_mobile",
    ],
    actions: ["review_details", "approve_branch", "reject_branch"],
    allowedRoles: ["admin"],
    columns: [
      { key: "branch_name", label: { ar: "الفرع", en: "Branch" } },
      { key: "store_name", label: { ar: "المتجر", en: "Store" } },
      { key: "city_name_ar", label: { ar: "المدينة", en: "City" } },
      { key: "governorate_ar", label: { ar: "المحافظة", en: "Governorate" } },
      {
        key: "manager_mobile",
        label: { ar: "رقم الفرع", en: "Branch contact" },
      },
      {
        key: "approval_status_ar",
        label: { ar: "الحالة", en: "Status" },
        tone: "status",
      },
      {
        key: "created_at",
        label: { ar: "تاريخ الإنشاء", en: "Created" },
        tone: "date",
      },
    ],
  },
  {
    id: "shipping-companies",
    href: "/admin/shipping-companies",
    icon: "Truck",
    mode: "table",
    source: "admin_merchant_shipping_companies_readable",
    sourceKind: "view",
    editableTable: "merchant_shipping_companies",
    orderBy: "created_at",
    title: { ar: "شركات الشحن", en: "Shipping companies" },
    description: {
      ar: "متابعة شركات الشحن التي أضافتها المتاجر وحالة استخدامها.",
      en: "Monitor shipping companies added by stores and their current status.",
    },
    searchKeys: ["store_name", "company_name"],
    actions: [], // Read-only for admins for now
    allowedRoles: ["admin", "support_agent"],
    supportPermission: "shipping_companies",
    columns: [
      { key: "store_name", label: { ar: "المتجر", en: "Store" } },
      { key: "company_name", label: { ar: "الشركة", en: "Company" } },
      { key: "batches_count", label: { ar: "عدد الدفعات", en: "Batches count" } },
      { key: "status_ar", label: { ar: "الحالة", en: "Status" }, tone: "status" },
      { key: "created_at", label: { ar: "تاريخ الإنشاء", en: "Created" }, tone: "date" },
    ],
  },
  {
    id: "users",
    href: "/admin/users",
    icon: "Users",
    mode: "table",
    source: "admin_users_readable",
    sourceKind: "view",
    editableTable: "users",
    orderBy: "created_at",
    title: { ar: "المستخدمون", en: "Users" },
    description: {
      ar: "إدارة حسابات المستخدمين والحظر والحذف وتحديث كلمات المرور بشكل آمن.",
      en: "Manage user accounts, blocking, deletion, and password updates securely.",
    },
    searchKeys: ["full_name", "mobile", "primary_email", "role_ar"],
    actions: [
      "block_user",
      "unblock_user",
      "set_user_password",
      "delete_user_account",
    ],
    allowedRoles: ["admin"],
    columns: [
      { key: "full_name", label: { ar: "الاسم", en: "Name" } },
      { key: "mobile", label: { ar: "رقم الجوال", en: "Mobile" } },
      { key: "primary_email", label: { ar: "البريد الإلكتروني", en: "Email" } },
      { key: "role_ar", label: { ar: "الصلاحية", en: "Role" }, tone: "status" },
      {
        key: "account_status_ar",
        label: { ar: "الحساب", en: "Account" },
        tone: "status",
      },
      { key: "created_at", label: { ar: "تاريخ الإنشاء", en: "Created" }, tone: "date" },
    ],
  },
  {
    id: "staff",
    href: "/admin/staff",
    icon: "Users",
    mode: "staff",
    title: {
      ar: "\u0627\u0644\u0641\u0631\u064a\u0642 \u0648\u0627\u0644\u0635\u0644\u0627\u062d\u064a\u0627\u062a",
      en: "Team and permissions",
    },
    description: {
      ar: "\u0625\u0636\u0627\u0641\u0629 \u0645\u062f\u064a\u0631 \u0623\u0648 \u0645\u0648\u0638\u0641 \u062f\u0639\u0645\u060c \u0648\u0643\u062a\u0627\u0628\u0629 \u0627\u0633\u0645 \u0627\u0644\u0631\u062a\u0628\u0629 \u0648\u062a\u062d\u062f\u064a\u062f \u0627\u0644\u0635\u0644\u0627\u062d\u064a\u0627\u062a.",
      en: "Add admins or support staff, set rank labels, and choose permissions.",
    },
    allowedRoles: ["admin"],
  },
  {
    id: "categories",
    href: "/admin/categories",
    icon: "Tags",
    mode: "table",
    source: "categories",
    sourceKind: "table",
    editableTable: "categories",
    editableFields: [
      "name_ar",
      "name_en",
      "parent_id",
      "display_order",
      "is_active",
    ],
    orderBy: "display_order",
    title: { ar: "الأقسام", en: "Categories" },
    description: {
      ar: "تقسيم الأقسام والمنتجات لتسهيل الوصول للمستخدمين وإدارة التطبيق.",
      en: "Organize categories and products so users can find them easily.",
    },
    searchKeys: ["name_ar", "name_en"],
    actions: ["edit_row", "toggle_active", "delete_row"],
    allowedRoles: ["admin"],
    columns: [
      { key: "name_ar", label: { ar: "الاسم بالعربي", en: "Arabic name" } },
      { key: "name_en", label: { ar: "الاسم بالإنجليزي", en: "English name" } },
      { key: "parent_id", label: { ar: "الرئيسي", en: "Parent" }, tone: "long" },
      { key: "display_order", label: { ar: "الترتيب", en: "Order" } },
      { key: "is_active", label: { ar: "مفعل", en: "Active" }, tone: "status" },
    ],
  },
  {
    id: "cities",
    href: "/admin/cities",
    icon: "Map",
    mode: "table",
    source: "cities",
    sourceKind: "table",
    editableTable: "cities",
    editableFields: [
      "country_ar",
      "country_en",
      "name_ar",
      "name_en",
      "governorate_ar",
      "governorate_en",
      "currency_code",
      "currency_name_ar",
      "currency_name_en",
      "display_order",
      "is_active",
    ],
    orderBy: "country_ar",
    title: { ar: "المدن والمناطق", en: "Cities and areas" },
    description: {
      ar: "تحديد المدن والمناطق التي سيتاح فيها التوصيل وإدارة رسوم الشحن.",
      en: "Manage delivery cities, operating areas, and shipping charges.",
    },
    searchKeys: [
      "country_ar",
      "country_en",
      "name_ar",
      "name_en",
      "governorate_ar",
      "governorate_en",
      "currency_code",
      "currency_name_ar",
      "currency_name_en",
    ],
    actions: ["edit_row", "toggle_active", "delete_row"],
    allowedRoles: ["admin"],
    columns: [
      { key: "country_ar", label: { ar: "الدولة", en: "Country" } },
      { key: "currency_name_ar", label: { ar: "العملة", en: "Currency" } },
      { key: "currency_code", label: { ar: "اختصار العملة", en: "Currency abbreviation" } },
      { key: "governorate_ar", label: { ar: "المحافظة", en: "Governorate" } },
      { key: "name_ar", label: { ar: "المدينة", en: "City" } },
      { key: "display_order", label: { ar: "الترتيب", en: "Order" } },
      { key: "name_en", label: { ar: "اسم المدينة بالإنجليزية", en: "English city name" } },
      {
        key: "is_active",
        label: { ar: "مفعل", en: "Active" },
        tone: "status",
      },
    ],
  },
  {
    id: "stores",
    hidden: true,
    href: "/admin/stores",
    icon: "Building2",
    mode: "table",
    source: "admin_active_merchants_readable",
    sourceKind: "view",
    orderBy: "updated_at",
    title: { ar: "المتاجر", en: "Stores" },
    description: {
      ar: "مراقبة المستخدمين والمتاجر والطلبات بشكل مستمر للحفاظ على الجودة.",
      en: "Store data, branches, products, and billing.",
    },
    searchKeys: [
      "store_name",
      "owner_name",
      "contact_mobile",
      "billing_preference_ar",
    ],
    allowedRoles: ["admin"],
    columns: [
      { key: "store_name", label: { ar: "المتجر", en: "Store" } },
      { key: "contact_mobile", label: { ar: "رقم التواصل", en: "Contact" } },
      {
        key: "approval_status_ar",
        label: { ar: "الموافقة", en: "Approval" },
        tone: "status",
      },
      {
        key: "billing_preference_ar",
        label: { ar: "الفواتير", en: "Billing" },
        tone: "status",
      },
      {
        key: "updated_at",
        label: { ar: "تاريخ التحديث", en: "Updated" },
        tone: "date",
      },
    ],
  },
  {
    id: "store-catalog",
    href: "/admin/store-catalog",
    icon: "Images",
    mode: "catalog",
    title: {
      ar: "مراجعة المتاجر والمنتجات",
      en: "Store and product review",
    },
    description: {
      ar: "عرض المتاجر والمنتجات بصرياً ومراجعة الصور والبيانات غير المكتملة.",
      en: "Browse stores and products, review images and incomplete information, and remove violations.",
    },
    allowedRoles: ["admin"],
  },
  {
    id: "orders",
    href: "/admin/orders",
    icon: "ClipboardList",
    mode: "table",
    source: "admin_orders_readable",
    sourceKind: "view",
    orderBy: "created_at",
    title: { ar: "الطلبات", en: "Orders" },
    description: {
      ar: "متابعة حالات الطلبات والتأكيد والدفع والقيم المالية المرتبطة بها.",
      en: "Track order status, confirmation, payment, and related amounts.",
    },
    searchKeys: ["buyer_name", "buyer_mobile", "store_name", "status_ar"],
    allowedRoles: ["admin", "support_agent"],
    supportPermission: "orders",
    columns: [
      { key: "buyer_name", label: { ar: "المشتري", en: "Buyer" } },
      { key: "store_name", label: { ar: "المتجر", en: "Store" } },
      {
        key: "status_ar",
        label: { ar: "الحالة", en: "Status" },
        tone: "status",
      },
      {
        key: "payment_status",
        label: { ar: "الدفع", en: "Payment" },
        tone: "status",
      },
      {
        key: "selected_subtotal_snapshot",
        label: { ar: "المجموع الفرعي", en: "Subtotal" },
        tone: "money",
      },
      { key: "created_at", label: { ar: "التاريخ", en: "Date" }, tone: "date" },
    ],
  },
  {
    id: "suspicious-matches",
    hidden: true,
    href: "/admin/suspicious-matches",
    icon: "SearchCheck",
    mode: "table",
    source: "admin_offer_items_readable",
    sourceKind: "view",
    orderBy: "created_at",
    title: { ar: "تطابقات غير مؤكدة", en: "Low confidence matches" },
    description: {
      ar: "مراجعة المنتجات التي لم يتأكد النظام من مطابقتها للطلبات قبل اعتمادها.",
      en: "Review products that were not confidently matched to requests before accepting them.",
    },
    searchKeys: [
      "store_name",
      "product_name",
      "requested_name",
      "matched_name_snapshot",
    ],
    allowedRoles: ["admin"],
    columns: [
      { key: "store_name", label: { ar: "المتجر", en: "Store" } },
      { key: "requested_name", label: { ar: "المطلوب", en: "Requested" } },
      { key: "matched_name_snapshot", label: { ar: "المطابق", en: "Matched" } },
      {
        key: "line_total_snapshot",
        label: { ar: "الإجمالي", en: "Total" },
        tone: "money",
      },
      {
        key: "match_confidence",
        label: { ar: "نسبة التأكد", en: "Confidence" },
        tone: "status",
      },
    ],
  },
  {
    id: "ai-reads",
    href: "/admin/ai-reads",
    icon: "FileScan",
    mode: "table",
    source: "admin_ai_reading_log",
    sourceKind: "view",
    orderBy: "created_at",
    title: { ar: "تحليلات المساعد الذكي", en: "Smart assistant analytics" },
    description: {
      ar: "مراجعة نتائج قراءة الصور والملفات وطلبات المستخدمين وحالات المعالجة.",
      en: "Review image and document readings, user requests, and processing status.",
    },
    searchKeys: [
      "owner_name",
      "owner_mobile",
      "reading_type_ar",
      "source_ar",
      "status_ar",
      "error_code",
    ],
    allowedRoles: ["admin"],
    columns: [
      { key: "owner_name", label: { ar: "المستخدم", en: "User" } },
      {
        key: "reading_type_ar",
        label: { ar: "نوع القراءة", en: "Reading type" },
        tone: "status",
      },
      {
        key: "source_ar",
        label: { ar: "المصدر", en: "Source" },
        tone: "status",
      },
      {
        key: "status_ar",
        label: { ar: "الحالة", en: "Status" },
        tone: "status",
      },
      { key: "confidence", label: { ar: "نسبة التأكد", en: "Confidence" } },
      { key: "error_code", label: { ar: "تفاصيل المشكلة", en: "Issue details" }, tone: "status" },
      { key: "created_at", label: { ar: "التاريخ", en: "Date" }, tone: "date" },
    ],
  },
  {
    id: "support",
    href: "/admin/support",
    icon: "Headphones",
    mode: "support",
    title: { ar: "الدعم", en: "Support" },
    description: {
      ar: "استلام المحادثات المحولة من المساعد الآلي وتعيينها وتصنيفها والرد عليها.",
      en: "Review conversations transferred from the automated assistant, assign them, label them, and reply.",
    },
    allowedRoles: ["admin", "support_agent"],
    supportPermission: "support_chats",
  },
  {
    id: "broadcast",
    href: "/admin/broadcast",
    icon: "BellRing",
    mode: "broadcast",
    title: { ar: "إرسال إشعار", en: "Send notification" },
    description: {
      ar: "إرسال إشعارات عربية وإنجليزية للمستخدمين مع اختيار النطاق والوجهة.",
      en: "Send a notification inside the app and to registered devices.",
    },
    allowedRoles: ["admin"],
  },
  {
    id: "ads",
    href: "/admin/ads",
    icon: "Images",
    mode: "table",
    source: "ads_banners",
    sourceKind: "table",
    editableTable: "ads_banners",
    editableFields: [
      "admin_name",
      "image_url",
      "target_url",
      "placement",
      "target_country_ar",
      "target_governorate_ar",
      "target_city_ar",
      "sort_order",
      "starts_at",
      "ends_at",
      "is_active",
    ],
    orderBy: "created_at",
    title: {
      ar: "\u0627\u0644\u0625\u0639\u0644\u0627\u0646\u0627\u062a",
      en: "Ads",
    },
    description: {
      ar: "إدارة الإعلانات في كروت منفصلة حسب مكان الظهور: واجهة العميل، دعوة صديق، وأعلى إعدادات المتجر.",
      en: "Manage ads in separate cards by placement: buyer home, invites, and store settings.",
    },
    searchKeys: [
      "admin_name",
      "image_url",
      "target_url",
      "placement",
      "target_country_ar",
      "target_governorate_ar",
      "target_city_ar",
    ],
    actions: ["edit_row", "toggle_active", "delete_row"],
    allowedRoles: ["admin"],
    columns: [
      {
        key: "admin_name",
        label: {
          ar: "اسم الإعلان",
          en: "Ad name",
        },
        tone: "long",
      },
      {
        key: "image_url",
        label: {
          ar: "\u0635\u0648\u0631\u0629 \u0627\u0644\u0625\u0639\u0644\u0627\u0646",
          en: "Image",
        },
        tone: "long",
      },
      {
        key: "target_url",
        label: {
          ar: "رابط الضغط (اختياري)",
          en: "Tap link (optional)",
        },
        tone: "long",
      },
      {
        key: "placement",
        label: {
          ar: "\u0645\u0643\u0627\u0646 \u0627\u0644\u0638\u0647\u0648\u0631",
          en: "Placement",
        },
        tone: "status",
      },
      { key: "target_country_ar", label: { ar: "الدولة", en: "Country" } },
      {
        key: "target_governorate_ar",
        label: { ar: "المحافظة", en: "Governorate" },
      },
      { key: "target_city_ar", label: { ar: "المدينة", en: "City" } },
      {
        key: "sort_order",
        label: {
          ar: "\u0627\u0644\u062a\u0631\u062a\u064a\u0628",
          en: "Order",
        },
      },
      {
        key: "is_active",
        label: { ar: "مفعل", en: "Active" },
        tone: "status",
      },
    ],
  },
  {
    id: "complaints",
    href: "/admin/complaints",
    icon: "MessagesSquare",
    mode: "complaints",
    source: "admin_support_complaints_readable",
    sourceKind: "view",
    orderBy: "created_at",
    title: { ar: "الشكاوى", en: "Complaints" },
    description: {
      ar: "متابعة الشكاوى الرسمية والتواصل مع الأطراف وتوثيق الحل والإجراء.",
      en: "Track formal complaints, contact involved parties, and document the resolution and final action.",
    },
    searchKeys: [
      "reporter_name",
      "reporter_mobile",
      "store_name",
      "title",
      "body",
      "status",
      "priority",
      "target_type",
    ],
    allowedRoles: ["admin", "support_agent"],
    supportPermission: "complaints",
    columns: [
      { key: "reporter_name", label: { ar: "المُبلغ", en: "Reporter" } },
      { key: "store_name", label: { ar: "المتجر", en: "Store" } },
      { key: "title", label: { ar: "العنوان", en: "Title" } },
      {
        key: "target_type",
        label: { ar: "النوع", en: "Type" },
        tone: "status",
      },
      { key: "status", label: { ar: "الحالة", en: "Status" }, tone: "status" },
      {
        key: "priority",
        label: { ar: "الأولوية", en: "Priority" },
        tone: "status",
      },
      { key: "created_at", label: { ar: "التاريخ", en: "Date" }, tone: "date" },
    ],
  },
  {
    id: "knowledge",
    href: "/admin/knowledge",
    icon: "BookOpen",
    mode: "table",
    source: "knowledge_base",
    sourceKind: "table",
    editableTable: "knowledge_base",
    editableFields: [
      "title_ar",
      "title_en",
      "content_ar",
      "content_en",
      "category",
      "is_active",
    ],
    orderBy: "updated_at",
    title: { ar: "معرفة المساعد الآلي", en: "Assistant knowledge" },
    description: {
      ar: "إدارة محتوى المساعد الآلي باللغتين وتحديثه حسب أسئلة المستخدمين.",
      en: "Manage the assistant's bilingual help content and refresh state.",
    },
    searchKeys: ["title_ar", "title_en", "content_ar", "category"],
    actions: ["edit_row", "toggle_active"],
    allowedRoles: ["admin", "support_agent"],
    supportPermission: "knowledge_base",
    columns: [
      { key: "title_ar", label: { ar: "العنوان", en: "Title" } },
      {
        key: "category",
        label: { ar: "القسم", en: "Category" },
        tone: "status",
      },
      { key: "is_active", label: { ar: "مفعل", en: "Active" }, tone: "status" },
      {
        key: "needs_embedding",
        label: { ar: "يحتاج تحديث المساعد", en: "Assistant update needed" },
        tone: "status",
      },
      {
        key: "updated_at",
        label: { ar: "تاريخ التحديث", en: "Updated" },
        tone: "date",
      },
    ],
  },
  {
    id: "reports",
    href: "/admin/reports",
    icon: "ChartNoAxesCombined",
    mode: "reports",
    title: { ar: "التقارير", en: "Reports" },
    description: {
      ar: "تقارير تشغيلية ومالية منظمة لمتابعة الطلبات والمتاجر والأقسام والإحالات.",
      en: "Organized operational and financial reports for orders, stores, categories, invitations, and commissions.",
    },
    allowedRoles: ["admin"],
  },
  {
    id: "content-moderation",
    href: "/admin/content-moderation",
    icon: "ShieldCheck",
    mode: "table",
    source: "content_moderation_terms",
    sourceKind: "table",
    editableTable: "content_moderation_terms",
    editableFields: [
      "term",
      "language",
      "match_type",
      "category",
      "severity",
      "notes",
      "is_active",
    ],
    orderBy: "updated_at",
    title: { ar: "مراقبة المحتوى", en: "Content moderation" },
    description: {
      ar: "إدارة الكلمات والعبارات المحظورة في الرسائل ومحتوى المنتجات.",
      en: "Manage blocked words and phrases used in messages and product content.",
    },
    searchKeys: [
      "term",
      "language",
      "match_type",
      "category",
      "severity",
      "notes",
    ],
    actions: ["edit_row", "toggle_active", "delete_row"],
    allowedRoles: ["admin"],
    columns: [
      { key: "term", label: { ar: "الكلمة", en: "Term" } },
      {
        key: "language",
        label: { ar: "اللغة", en: "Language" },
        tone: "status",
      },
      {
        key: "match_type",
        label: { ar: "نوع التطابق", en: "Match type" },
        tone: "status",
      },
      {
        key: "category",
        label: { ar: "القسم", en: "Category" },
        tone: "status",
      },
      {
        key: "severity",
        label: { ar: "الإجراء", en: "Action" },
        tone: "status",
      },
      { key: "is_active", label: { ar: "مفعل", en: "Active" }, tone: "status" },
      {
        key: "updated_at",
        label: { ar: "تاريخ التحديث", en: "Updated" },
        tone: "date",
      },
    ],
  },
  {
    id: "monetization",
    href: "/admin/monetization",
    icon: "BadgeDollarSign",
    mode: "monetization",
    source: "feature_flags",
    sourceKind: "table",
    editableTable: "feature_flags",
    editableFields: [
      "description_ar",
      "description_en",
      "is_enabled",
      "configuration",
    ],
    orderBy: "key",
    title: { ar: "تحقيق الدخل", en: "Monetization" },
    description: {
      ar: "إدارة الاشتراكات والدفع والعمولات وفترات السماح من مكان واحد.",
      en: "Manage subscriptions, payments, commissions, and grace periods in one place.",
    },
    searchKeys: ["key", "description_ar", "description_en"],
    actions: ["edit_row", "toggle_active"],
    allowedRoles: ["admin"],
  },
  {
    id: "payments",
    href: "/admin/payments",
    icon: "CreditCard",
    mode: "table",
    source: "admin_payment_transactions_readable",
    sourceKind: "view",
    orderBy: "created_at",
    title: { ar: "المدفوعات", en: "Payments" },
    description: {
      ar: "متابعة عمليات الدفع وحالاتها وطرق التحصيل والمستحقات المرتبطة بها.",
      en: "Track payment transactions, their status, collection methods, and related dues.",
    },
    searchKeys: [
      "user_name",
      "store_name",
      "provider",
      "status",
      "external_reference",
    ],
    allowedRoles: ["admin"],
    columns: [
      { key: "user_name", label: { ar: "المستخدم", en: "User" } },
      { key: "store_name", label: { ar: "المتجر", en: "Store" } },
      {
        key: "provider",
        label: { ar: "مزود الخدمة", en: "Provider" },
        tone: "status",
      },
      { key: "amount", label: { ar: "المبلغ", en: "Amount" }, tone: "money" },
      { key: "status", label: { ar: "الحالة", en: "Status" }, tone: "status" },
      { key: "created_at", label: { ar: "التاريخ", en: "Date" }, tone: "date" },
    ],
  },
  {
    id: "referrals",
    href: "/admin/referrals",
    icon: "Gift",
    mode: "table",
    source: "admin_referral_rewards_readable",
    sourceKind: "view",
    orderBy: "created_at",
    title: { ar: "الإحالات والمكافآت", en: "Referrals and rewards" },
    description: {
      ar: "مراقبة دعوات المستخدمين ونظام الإحالة وتقديم المكافآت الترويجية.",
      en: "Track invitation codes, confirmed registrations, referrals, and promotional rewards.",
    },
    searchKeys: [
      "referrer_name",
      "rewarded_user_name",
      "referral_code",
      "delivery_status",
    ],
    allowedRoles: ["admin"],
    columns: [
      { key: "referrer_name", label: { ar: "المُحيل", en: "Referrer" } },
      {
        key: "rewarded_user_name",
        label: { ar: "المستخدم المُكافأ", en: "Rewarded user" },
      },
      {
        key: "referral_code",
        label: { ar: "الكود", en: "Code" },
        tone: "status",
      },
      {
        key: "reward_type",
        label: { ar: "المكافأة", en: "Reward" },
        tone: "status",
      },
      {
        key: "delivery_status",
        label: { ar: "التوصيل", en: "Delivery" },
        tone: "status",
      },
      { key: "created_at", label: { ar: "التاريخ", en: "Date" }, tone: "date" },
    ],
  },
  {
    id: "audit",
    hidden: true,
    href: "/admin/audit",
    icon: "ShieldCheck",
    mode: "table",
    source: "admin_audit_logs_readable",
    sourceKind: "view",
    orderBy: "created_at",
    title: { ar: "سجل الحركات", en: "Audit logs" },
    description: {
      ar: "سجل كامل وتفصيلي لكل الإجراءات لضمان التتبع ومعرفة الفاعل متى شاء.",
      en: "Sensitive actions appear here for review.",
    },
    searchKeys: [
      "actor_name",
      "actor_email",
      "action",
      "target_table",
      "target_id",
    ],
    allowedRoles: ["admin"],
    columns: [
      { key: "actor_name", label: { ar: "الفاعل", en: "Actor" } },
      { key: "action", label: { ar: "الإجراء", en: "Action" }, tone: "status" },
      {
        key: "target_table",
        label: { ar: "الجدول", en: "Table" },
        tone: "status",
      },
      { key: "target_id", label: { ar: "الهدف", en: "Target" }, tone: "long" },
      { key: "created_at", label: { ar: "التاريخ", en: "Date" }, tone: "date" },
    ],
  },
];

export function findSection(id?: string) {
  return sections.find((section) => section.id === id) ?? sections[0];
}

export function sectionIsAllowed(
  section: SectionConfig,
  profile: AdminProfile | null,
) {
  if (section.hidden) {
    return false;
  }
  if (!profile) {
    return false;
  }

  if (profile.role === "admin" && profile.permissions.__limit_admin !== true) {
    return true;
  }

  const permissionKey = permissionKeyForSection(section);
  if (profile.permissions[permissionKey] === true) {
    return true;
  }

  if (section.allowedRoles && !section.allowedRoles.includes(profile.role)) {
    return false;
  }

  return profile.role === "admin" && profile.permissions.__limit_admin !== true;
}

export function visibleSections(profile: AdminProfile | null) {
  return sections.filter((section) => sectionIsAllowed(section, profile));
}

function permissionKeyForSection(section: SectionConfig) {
  return section.supportPermission ?? section.id.replace(/-/g, "_");
}
